### ISSUE TITLE
Create item detail page

### ISSUE THREAD

**Issue by Wings30306** [Wings30306/webshop-mvp#2]
### User Story
As a customer, I can see more details about the item, so that I can decide whether to buy it.

### Acceptance Criteria

- [x] Every item is displayed on its own page
- [ ] Users can easily view the detail page for each item displayed on the home page

### Tasks

- [x] Create template for detail page
- [x] Create view for detail page
- [ ] Link detail page view to url
- [x] Create link to detail page on the item name in the homepage
