### ISSUE TITLE
Add an item to the cart

### ISSUE THREAD

**Issue by Wings30306** [Wings30306/webshop-mvp#3]
### User story
As a customer, I can select the amount of items I want on the item detail page, so that I can buy multiples of the same item, e.g. 10 flasks for myself and my colleagues.

### Acceptance criteria

- [ ] Item detail page has a form with a number field (amount) and a submit button
- [ ] On submit, the item id and its requested amount are sent to the cart
- [ ] The cart page displays the item name, amount, individual price and total for this item

### Tasks
- [ ] Create a Cart template
- [ ] Save item id and amount 
- [ ] Display the item name, amount, individual item price and
